- name: install and configure nginx server
  hosts: all
  become: true  

  tasks:
   - name: update yum 
     yum: 
      name: '*'
      state: latest
     when: ansible_os_family == "RedHat" 
    
   - name: update apt
     apt:
      update_cache: true
      upgrade: dist
     when: ansible_os_family == "Debian"   
  
   - name: install nginx on amazon linux
     yum: 
      name: nginx
      state: present
     when: ansible_os_family == "RedHat"
   
   - name: install nginx on ubuntu
     apt:
      name: nginx
      state: present
     when: ansible_os_family == "Debian"   
  
   - name: start and enable nginx 
     service: 
      name: nginx
      state: started
      enabled: true  

   - name: check nginx status 
     shell: systemctl status nginx
     register: nginx_status
   
   - name: display nginx status
     debug:
      msg: "Nginx status: {{ nginx_status.stdout }}"   
